Improvements
joaquinTop/targetMVD-web-react pull request #1
Opened 2016-12-20 16:44 UTC by joaquinTop

This PR contains, several improvements related to the feedback. 
- Ajax calls now are in actions so that triggers different events in store.
- Delete Reducer for maintaining user information, now this info is stored in the states of each form.
- Session Reducer manages the session information, controlling if user is logged in for private pages.

2016-12-21 14:07 UTC, bernabe9 requested changes

2016-12-21 14:07 UTC, bernabe9 commented on src/actions/newTargetActions.js
> +  return {type:types.UPDATE_FREE_TARGET, fieldName:fieldName, value:value};
Always leave a blank space after the `:`

Also, you can use `Property shorthand` to avoid write the property twice(http://es6-features.org/#PropertyShorthand)

So, the return should be:
`return {type: types.UPDATE_FREE_TARGET, fieldName, value};`

2016-12-21 14:07 UTC, bernabe9 commented on src/client/TargetsServerClient.js
> +        debugger;
remove it

2016-12-21 14:07 UTC, bernabe9 commented on src/client/UsersServerClient.js
> +        console.log(data);
This `console.log` is not necessary. Always use the console logs for show errors or for specific prupose

2016-12-21 14:07 UTC, bernabe9 commented on src/components/home/SideBarContainer.js
> +      // updateTargetList={props.actions.createTarget}
remove commented lines

2016-12-21 14:07 UTC, bernabe9 commented on src/components/signin/SignInForm.js
>        "user":{
Don't use the strings for the property names.

For example here should be:
```
  user: {
    email: this.state.email,
    password: this.state.password
  }
```

2016-12-21 14:07 UTC, bernabe9 commented on src/components/signup/SignUpForm.js
>        "user":{
same here

2016-12-21 14:07 UTC, bernabe9 commented on src/containers/SignInPage.js
> +  if (props.session.isLoggedIn == true) {
Just `props.session.isLoggedIn` will work

2016-12-21 14:07 UTC, bernabe9 commented on src/containers/SignInPage.js
> +    return null;
I think this return is not necessary 🤔

2016-12-21 14:07 UTC, bernabe9 commented on src/reducers/targetReducer.js
> +          id: el.id,
These params are the same that you used above. Maybe you could make a function to return these params in order of don't repeat code. Just a suggestion

2016-12-23 16:36 UTC, joaquinTop commented on src/containers/SignInPage.js
> +    return null;
If i remove the return null statement, i get this error : "Uncaught Error: A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object." And the  app would go blank.

2016-12-26 13:04 UTC, bernabe9 approved these changes

2016-12-26 13:04 UTC, merged