Feature/edit target
joaquinTop/targetMVD-web-react pull request #16
Opened 2017-02-16 14:55 UTC by joaquinTop

### Feature: *Edit Target*
* Added put request for updating selected target
* Added buttons for delete & update target
* Message displayed when target is successfully updated

2017-02-16 15:31 UTC, felipegarcia92 requested changes

2017-02-16 15:31 UTC, felipegarcia92 commented on src/actions/targetActions.js
> +      dispatch(createAlert("SideBarContainer", "Target successfully created", "success"));
I looked at the code of the `createAlert` function and I think it's a good idea to refactor those "SideBarContainer" and "success" flags to constants.

I'd declare a goals object with keys, for example:
```
const goals = {
  sidebar: 'SidebarContainer',
  ...etc
}
```
in a constants file, then import it and use it like `constants.sidebar`.

Also, remember that when writing JS, single quotes `'` are preferred.

I suggest you do the same with the alert types, so you don't have to use explicit strings all over the code.

2017-02-16 15:31 UTC, felipegarcia92 commented on src/components/common/Map.js
> +      const color = isSelectedTarget ? 'rgb(48, 188, 247)' : 'rgb(239, 197, 55)';
Declare the color strings as a constants saying more or less what color is it.

2017-02-16 15:31 UTC, felipegarcia92 commented on src/components/targets/TargetForm.js
> +
Delete the extra new lines here, I don't think they're necessary

2017-02-16 15:31 UTC, felipegarcia92 commented on src/components/targets/TargetForm.js
> +    if (!enabled && formMode === "New") {
Refactor the form modes into constants, just like the other comment above.

2017-02-16 15:31 UTC, felipegarcia92 commented on src/components/home/SideBarContainer.js
> +    case "Home":{
Reafactor these content strings into a constant, like the comment above.

2017-02-16 16:08 UTC, bernabe9 requested changes

2017-02-16 16:08 UTC, bernabe9 commented on src/components/targets/TargetForm.js
> +    const { deleteTargetAction, currentTarget } = this.props;
You are use only the `id` of the `currentTarget`, so you can use a shortcut here:
`const { deleteTargetAction, currentTarget: { id } } = this.props;`

2017-02-17 14:05 UTC, felipegarcia92 approved these changes
I like this solution and will probably the enum library on future projects

2017-02-17 14:12 UTC, bernabe9 approved these changes

2017-02-17 14:12 UTC, merged