Ui improvements
joaquinTop/targetMVD-web-react pull request #6
Opened 2017-01-05 18:28 UTC by joaquinTop

This branch has several ui improvements such as: 
- a new responsive landing page 
- alert reducer for displaying messages across the app 
- several new icons for targets and menus,
- dropdown for displaying topics 
- animations 
- new styles  
- other changes.

2017-01-10 13:37 UTC, bernabe9 requested changes

2017-01-10 13:37 UTC, bernabe9 commented on src/actions/alertActions.js
> +  return {type: types.CREATE_ALERT, goal, text, alertType};
leave a blank space between the brackets

2017-01-10 13:37 UTC, bernabe9 commented on src/actions/alertActions.js
> +  return {type: types.DELETE_ALERT};
leave a blank space between the brackets

2017-01-10 13:37 UTC, bernabe9 commented on src/actions/sessionActions.js
> +// import topicClient from '../client/TopicsServerClient';
remove this commented line

2017-01-10 13:37 UTC, bernabe9 commented on src/client/TopicsServerClient.js
> +        const {data} = res;
leave a blank space between the brackets

2017-01-10 13:37 UTC, bernabe9 commented on src/components/common/LandingRightSide.js
> +          {/* <div className="rectangle"></div> */}
remove it

2017-01-10 13:37 UTC, bernabe9 commented on src/components/common/LandingRightSide.js
> +          {/* <div className="rectangle"></div> */}
same

2017-01-10 13:37 UTC, bernabe9 commented on src/components/common/LandingRightSide.js
> +        <div className="column-right-half">
the only difference between `column-right-half` and `coloumn-right` is one prop.
you can manage this with a normal media query instead of use `react-responsive`

2017-01-10 13:37 UTC, bernabe9 commented on src/components/common/Map.js
> +        opts['icon'] = icon;
use dot notation: `opts.icon = icon`

2017-01-10 13:37 UTC, bernabe9 commented on src/components/home/SideBarContainer.js
> +      {/* resetFreeTarget={props.actions.resetFreeTarget} */}
remove this line

2017-01-10 13:37 UTC, bernabe9 commented on src/components/home/SideBarContainer.js
>  function mapStateToProps(state) {
Check this trick to simplify the code:
```
const mapStateToProp = ({ newTarget, session, alert }) => ({
  newTarget,
  session,
  alert
})
```

2017-01-10 13:37 UTC, bernabe9 commented on src/components/targets/TargetForm.js
> +    // const opts = {};
remove commented code

2017-01-11 17:12 UTC, bernabe9 requested changes

2017-01-11 17:12 UTC, bernabe9 commented on src/components/targets/TargetForm.js
> +    const topicPlaceholder = (defaultOption !== '' ? defaultOption:"What do you want to talk about?");
You can do:
`const topicPlaceholder = defaultOption || 'What do you want to talk about?';`

2017-01-11 17:12 UTC, bernabe9 commented on src/components/targets/TargetForm.js
> +          <TextInput id="areaLength" onChange={this.onFieldChange} style="custom-target-input" name="radius" areaLength={"number"} value={this.props.currentTarget.radius} required={"true"} autofocus=
This line is too long.
You can split like this:
```
<TextInput
  id="areaLength"
  onChange={this.onFieldChange}
  style="custom-target-input"
  name="radius"
  areaLength={"number"}
  value={this.props.currentTarget.radius}
  required={"true"}
  autofocus={"true"}
/>
  <TextInput /><br/>
```

The same with all the lines that are too long.

Please, try to read https://github.com/airbnb/javascript/tree/master/react#alignment
Also, there are others good practices in this guide

2017-01-11 17:12 UTC, bernabe9 commented on src/containers/SignInPage.js
> +      <SignInForm signInAction={props.actions.signIn} signInWithFBAction={props.actions.signInWithFB} style="column-half-media"/>
split this line

2017-01-11 17:12 UTC, bernabe9 commented on src/containers/SignUpPage.js
> +  return {
write in line: `return { session };`

2017-01-11 17:12 UTC, bernabe9 commented on src/reducers/initialState.js
> +  alert:{
leave a blank space after `:`

2017-01-11 17:12 UTC, bernabe9 commented on src/styles/base/_column.scss
> +	@media (min-width: 1224px) {
use 2 spaces as the tab length

2017-01-11 17:12 UTC, bernabe9 commented on src/styles/base/_column.scss
> +		height: 100%;
I think you don't need to redefine all the props, just redefine `width: 50%`

2017-01-11 17:12 UTC, bernabe9 commented on src/styles/base/_dropdown.scss
> +.Dropdown-root {
use lowercase

2017-01-11 17:12 UTC, bernabe9 commented on src/styles/base/_outer.scss
> +  position:absolute;
leave a blank space after `:`

2017-01-11 17:12 UTC, bernabe9 commented on src/styles/components/_map.scss
> +	margin-left:318px;
check this line alignment

2017-01-11 17:12 UTC, bernabe9 commented on src/styles/components/_sideBarContainer.scss
> +	height: 30px;
same

2017-01-11 17:12 UTC, bernabe9 commented on src/styles/components/_sideBarContainer.scss
> +	height: 28px;
same

2017-01-11 17:12 UTC, bernabe9 commented on src/styles/components/_sideBarContainer.scss
> +  margin-bottom: 0px;
use margin shorthand: `margin: top right bottom left`
Also, don't use units for the zero value

2017-01-11 17:12 UTC, bernabe9 commented on src/styles/components/_signInForm.scss
> +	font-family: sans-serif;
The font-family generally is defined in the html body, it's weird to define for each class

2017-01-11 17:12 UTC, bernabe9 commented on src/styles/components/_signInForm.scss
> +	margin-top: 24px;
use margin shorthand

2017-01-11 17:12 UTC, bernabe9 commented on src/styles/components/_signInForm.scss
> +	margin-top: 49px;
same

2017-01-11 17:12 UTC, bernabe9 commented on src/styles/components/_signUpForm.scss
> +  margin-bottom: 21px;
same

2017-01-11 17:12 UTC, bernabe9 commented on src/styles/components/_signUpForm.scss
> +	margin-top: 17px;
same

2017-01-11 17:12 UTC, bernabe9 commented on src/styles/components/_targetForm.scss
> +  margin-top: 0px;
don't use units for the zero value

2017-01-11 17:12 UTC, bernabe9 commented on src/styles/base/_dropdown.scss
> +  border: solid 0.5px #000000;
Use the colors defined here `src/styles/utils/_palette.scss`

2017-01-12 17:04 UTC, joaquinTop commented on src/styles/base/_dropdown.scss
> +.Dropdown-root {
In this case, i am using 'react-dropdown' component which styles are implicit. If i change the name to lowercase, the component would not recognize it.

2017-01-12 18:42 UTC, joaquinTop commented on src/styles/base/_column.scss
> +	@media (min-width: 1224px) {
I think the indentation is being shown incorrectly on Github's page. This file shows how alignment is correct: https://github.com/joaquinTop/targetMVD-web-react/blob/ui_improvements/src/styles/base/_column.scss

2017-01-12 20:02 UTC, bernabe9 approved these changes

2017-01-12 20:02 UTC, merged